const endpoints = {
  assignments: 'assignments',
  calendarEvents: 'calendar-events',
  classrooms: 'hostel-rooms',
  courses: 'courses',
  departments: 'departments',
  designations: 'designations',
  organizations: 'organizations',
  hrDocuments: 'hr-documents',
  employeeAttendance: 'employee-attendance',
  employees: 'employees',
  examinations: 'examinations',
  examinationAttendance: 'examination-attendance',
  seatingPlans: 'seating-plans',
  invigilatorAssignments: 'invigilator-assignments',
  examinationReports: 'examination-reports',
  feePayments: 'fee-payments',
  fees: 'fees',
  payments: 'payments',
  receipts: 'receipts',
  scholarships: 'scholarships',
  gradecards: 'grade-cards',
  leads: 'leads',
  lectureAttendance: 'lecture-attendance',
  lectureNotes: 'lecture-notes',
  lectureSchedules: 'lecture-schedules',
  libraryBooks: 'libraries/library-books',
  libraryMembers: 'libraries/library-members',
  libraryIssues: 'libraries/library-issues',
  libraryFines: 'libraries/library-fines',
  libraryReservations: 'libraries/library-reservations',
  libraryRenewals: 'libraries/library-renewals',
  libraryLosses: 'libraries/library-losses',
  libraryDamages: 'libraries/library-damages',
  hostels: 'hostels',
  hostelRooms: 'hostel-rooms',
  hostelAllocations: 'hostel-allocations',
  hostelVisitors: 'hostel-visitors',
  hostelFees: 'hostel-fees',
  hostelComplaints: 'hostel-complaints',
  hostelWardens: 'hostel-wardens',
  maintenanceRequests: 'maintenance-requests',
  roomInspections: 'room-inspections',
  transportVehicles: 'transport-vehicles',
  transportDrivers: 'transport-drivers',
  transportConductors: 'transport-conductors',
  transportRoutes: 'transport-routes',
  transportStops: 'transport-stops',
  studentTransportAssignments: 'student-transport-assignments',
  employeeTransportAssignments: 'employee-transport-assignments',
  vehicleAttendance: 'vehicle-attendance',
  fuelEntries: 'fuel-entries',
  maintenanceRecords: 'maintenance-records',
  promotions: 'student-promotions',
  // legacy alias: `lectures` kept for backward compatibility — prefer `lectureSchedules`
  lectures: 'lecture-schedules',
  practicalMarks: 'practical-marks',
  internalMarks: 'internal-marks',
  questionBank: 'question-bank',
  results: 'results',
  securityGuardAttendance: 'security-guard-attendance',
  securityGuards: 'security-guards',
  visitors: 'visitors',
  gatePasses: 'gate-passes',
  vehicles: 'vehicles',
  incidents: 'incidents',
  sections: 'sections',
  semesters: 'semesters',
  studentAttendance: 'student-attendance',
  students: 'students',
  subjects: 'subjects',
  assetCategories: 'asset-categories',
  assets: 'assets',
  vendors: 'vendors',
  purchaseOrders: 'purchase-orders',
  stockMovements: 'stock-movements',
  assetAssignments: 'asset-assignments',
  subjectAssignments: 'subject-assignments',
  syllabi: 'syllabi',
  teacherAttendance: 'teacher-attendance',
  teachers: 'teachers',
  teacherCourseAssignments: 'teacher-course-assignments',
  teacherSemesterAssignments: 'teacher-semester-assignments',
  teacherSubjectAssignments: 'teacher-subject-assignments',
  teacherWorkloads: 'teacher-workloads',
  timetables: 'timetables',
  transcripts: 'transcripts',
};

export function getEndpoint(resource) {
  return endpoints[resource] || resource;
}

export default endpoints;
