"""Generic Alembic script template.
Revision ID: 46e7886742ac
Revises: 
Create Date: 2026-07-03 12:31:55.608005
"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46e7886742ac'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
