"""Generic Alembic script template.
Revision ID: eedf758aff7f
Revises: 46e7886742ac
Create Date: 2026-07-07 09:20:48.134820
"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eedf758aff7f'
down_revision = '46e7886742ac'
branch_labels = None
depends_on = None


def upgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rooms', sa.Column('building', sa.String(length=128), nullable=True))
    op.add_column('rooms', sa.Column('floor', sa.String(length=32), nullable=True))
    op.add_column('rooms', sa.Column('has_projector', sa.Boolean(), nullable=False))
    op.add_column('rooms', sa.Column('has_lab', sa.Boolean(), nullable=False))
    op.add_column('rooms', sa.Column('has_ac', sa.Boolean(), nullable=False))
    op.add_column('rooms', sa.Column('status', sa.Enum('Active', 'Maintenance', 'Inactive', name='room_status'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rooms', 'status')
    op.drop_column('rooms', 'has_ac')
    op.drop_column('rooms', 'has_lab')
    op.drop_column('rooms', 'has_projector')
    op.drop_column('rooms', 'floor')
    op.drop_column('rooms', 'building')
    # ### end Alembic commands ###
