from app.models.academic.models import (
    AcademicClass,
    AcademicYear,
    AssessmentConfig,
    AssessmentGradeSetup,
    AssessmentGroup,
    AssessmentGroupItem,
    AttendanceMarksConfig,
    AttendanceMarksSetup,
    Course,
    Department,
    Designation,
    Section,
    Semester,
    Subject,
)

__all__ = [
    "AcademicClass",
    "AcademicYear",
    "AssessmentConfig",
    "AssessmentGradeSetup",
    "AssessmentGroup",
    "AssessmentGroupItem",
    "AttendanceMarksConfig",
    "AttendanceMarksSetup",
    "Course",
    "Department",
    "Designation",
    "Section",
    "Semester",
    "Subject",
]
