import {
  BookOpen,
  BriefcaseBusiness,
  CalendarDays,
  ClipboardCheck,
  ClipboardList,
  Clock3,
  FileBadge2,
  FileCheck2,
  GraduationCap,
  Layers3,
  ListChecks,
  NotebookPen,
  ScanSearch,
  School,
  Settings2,
  Users,
  UsersRound,
} from 'lucide-react';

export const academicsModuleConfig = [
  {
    title: 'Subject',
    description: 'Manage academic subjects and classifications',
    icon: BookOpen,
    route: '/subjects',
    permission: 'subjects',
    status: 'existing',
  },
  {
    title: 'Faculty Mapping',
    description: 'Map faculty to academic assignments',
    icon: UsersRound,
    route: '/settings/institute/academics/faculty-mapping',
    permission: 'settings',
    status: 'placeholder',
  },
  {
    title: 'Subject College Mapping',
    description: 'Associate subjects across colleges',
    icon: Layers3,
    route: '/settings/institute/academics/subject-college-mapping',
    permission: 'settings',
    status: 'placeholder',
  },
  {
    title: 'Subject College Mapping V2',
    description: 'Advanced subject-college mapping workflow',
    icon: Layers3,
    route: '/settings/institute/academics/subject-college-mapping-v2',
    permission: 'settings',
    status: 'placeholder',
  },
  {
    title: 'Assessment Master',
    description: 'Configure assessment definitions',
    icon: ClipboardCheck,
    route: '/settings/institute/academics/assessment-master',
    permission: 'settings',
    status: 'placeholder',
  },
  {
    title: 'Assessment Grade Setup',
    description: 'Define grade scales and performance bands',
    icon: FileBadge2,
    route: '/settings/institute/academics/assessment-grade-setup',
    permission: 'settings',
    status: 'placeholder',
  },
  {
    title: 'Attendance Marks Setup',
    description: 'Set attendance mark calculation rules',
    icon: ListChecks,
    route: '/settings/institute/academics/attendance-marks-setup',
    permission: 'settings',
    status: 'placeholder',
  },
  {
    title: 'Assessment Config',
    description: 'Control assessment behavior and settings',
    icon: Settings2,
    route: '/settings/institute/academics/assessment-config',
    permission: 'settings',
    status: 'placeholder',
  },
  {
    title: 'Assessment Group',
    description: 'Group assessments by criteria',
    icon: NotebookPen,
    route: '/settings/institute/academics/assessment-group',
    permission: 'settings',
    status: 'placeholder',
  },
  {
    title: 'Assessment Config College Wise',
    description: 'College-specific assessment configuration',
    icon: School,
    route: '/settings/institute/academics/assessment-config-college-wise',
    permission: 'settings',
    status: 'placeholder',
  },
  {
    title: 'Assessment Group College Wise',
    description: 'College-specific assessment grouping',
    icon: School,
    route: '/settings/institute/academics/assessment-group-college-wise',
    permission: 'settings',
    status: 'placeholder',
  },
  {
    title: 'Assign Subject',
    description: 'Assign subjects to departments and programs',
    icon: GraduationCap,
    route: '/students/allocate-subject',
    permission: 'students',
    status: 'existing',
  },
  {
    title: 'Assign Roll Number',
    description: 'Assign roll numbers to students',
    icon: Users,
    route: '/students/update-roll',
    permission: 'students',
    status: 'existing',
  },
  {
    title: 'Lecture Schedule Mapper',
    description: 'Link lecture schedules to academic plans',
    icon: CalendarDays,
    route: '/lectures',
    permission: 'lectureNotes',
    status: 'existing',
  },
  {
    title: 'Time Table',
    description: 'Create and manage institution timetables',
    icon: Clock3,
    route: '/attendance/timetable',
    permission: 'timetable',
    status: 'existing',
  },
  {
    title: 'Employee Calendar List',
    description: 'Track employee calendars and academic commitments',
    icon: CalendarDays,
    route: '/employees/attendance-calendar',
    permission: 'employees',
    status: 'existing',
  },
  {
    title: 'Remark Setup List',
    description: 'Maintain academic remarks and notes',
    icon: ClipboardList,
    route: '/settings/institute/academics/remark-setup-list',
    permission: 'settings',
    status: 'placeholder',
  },
  {
    title: 'Result Setup List',
    description: 'Set up result configuration and output rules',
    icon: FileCheck2,
    route: '/settings/institute/academics/result-setup-list',
    permission: 'settings',
    status: 'placeholder',
  },
  {
    title: 'Allocate Subjects',
    description: 'Allocate subjects across classes and strands',
    icon: BriefcaseBusiness,
    route: '/students/allocate-subjects',
    permission: 'students',
    status: 'existing',
  },
  {
    title: 'Attendance Remarks',
    description: 'Manage attendance remarks and status text',
    icon: ScanSearch,
    route: '/settings/institute/academics/attendance-remarks',
    permission: 'settings',
    status: 'placeholder',
  },
];
