from pathlib import Path
import json

base = Path('d:/Users/pop/Desktop/new pr/src/pages')
base.mkdir(parents=True, exist_ok=True)

pages = [
    {
        'file': 'StudentCertificatesPage.jsx',
        'component': 'StudentCertificatesPage',
        'title': 'Student certificates',
        'subtitle': 'Generate and track certificates for completed academic milestones.',
        'resource': 'students',
        'itemLabel': 'certificate',
        'initialValues': {'name': '', 'certificateType': 'Completion', 'issueDate': '', 'status': 'Issued'},
        'fields': [
            {'name': 'name', 'label': 'Student name'},
            {'name': 'certificateType', 'label': 'Certificate type'},
            {'name': 'issueDate', 'label': 'Issue date', 'type': 'date'},
            {'name': 'status', 'label': 'Status', 'type': 'select', 'options': [{'value': 'Issued', 'label': 'Issued'}, {'value': 'Pending', 'label': 'Pending'}, {'value': 'Revoked', 'label': 'Revoked'}]},
        ],
        'columns': [
            {'key': 'name', 'label': 'Student'},
            {'key': 'certificateType', 'label': 'Certificate type'},
            {'key': 'issueDate', 'label': 'Issue date'},
            {'key': 'status', 'label': 'Status'},
        ],
    },
    {
        'file': 'AlumniPage.jsx',
        'component': 'AlumniPage',
        'title': 'Alumni directory',
        'subtitle': 'Maintain alumni records and graduation history for the institution.',
        'resource': 'students',
        'itemLabel': 'alumni record',
        'initialValues': {'name': '', 'graduationYear': '', 'department': '', 'email': '', 'status': 'Active'},
        'fields': [
            {'name': 'name', 'label': 'Student name'},
            {'name': 'graduationYear', 'label': 'Graduation year', 'type': 'number'},
            {'name': 'department', 'label': 'Department'},
            {'name': 'email', 'label': 'Email', 'type': 'email'},
            {'name': 'status', 'label': 'Status', 'type': 'select', 'options': [{'value': 'Active', 'label': 'Active'}, {'value': 'Inactive', 'label': 'Inactive'}]},
        ],
        'columns': [
            {'key': 'name', 'label': 'Name'},
            {'key': 'graduationYear', 'label': 'Graduation year'},
            {'key': 'department', 'label': 'Department'},
            {'key': 'email', 'label': 'Email'},
            {'key': 'status', 'label': 'Status'},
        ],
    },
    {
        'file': 'LibraryBooksPage.jsx',
        'component': 'LibraryBooksPage',
        'title': 'Library books',
        'subtitle': 'Track book inventory, ISBNs and availability in the library.',
        'resource': 'libraryBooks',
        'itemLabel': 'book',
        'initialValues': {'title': '', 'author': '', 'isbn': '', 'category': 'General', 'copies': '1', 'status': 'Available'},
        'fields': [
            {'name': 'title', 'label': 'Book title'},
            {'name': 'author', 'label': 'Author'},
            {'name': 'isbn', 'label': 'ISBN'},
            {'name': 'category', 'label': 'Category'},
            {'name': 'copies', 'label': 'Copies', 'type': 'number'},
            {'name': 'status', 'label': 'Status', 'type': 'select', 'options': [{'value': 'Available', 'label': 'Available'}, {'value': 'Issued', 'label': 'Issued'}, {'value': 'Damaged', 'label': 'Damaged'}]},
        ],
        'columns': [
            {'key': 'title', 'label': 'Title'},
            {'key': 'author', 'label': 'Author'},
            {'key': 'isbn', 'label': 'ISBN'},
            {'key': 'category', 'label': 'Category'},
            {'key': 'copies', 'label': 'Copies'},
            {'key': 'status', 'label': 'Status'},
        ],
    },
    {
        'file': 'LibraryCategoriesPage.jsx',
        'component': 'LibraryCategoriesPage',
        'title': 'Library categories',
        'subtitle': 'Organize the library catalogue by category and subject.',
        'resource': 'libraryCategories',
        'itemLabel': 'category',
        'initialValues': {'name': '', 'description': '', 'status': 'Active'},
        'fields': [
            {'name': 'name', 'label': 'Category name'},
            {'name': 'description', 'label': 'Description', 'type': 'textarea'},
            {'name': 'status', 'label': 'Status', 'type': 'select', 'options': [{'value': 'Active', 'label': 'Active'}, {'value': 'Inactive', 'label': 'Inactive'}]},
        ],
        'columns': [
            {'key': 'name', 'label': 'Category'},
            {'key': 'description', 'label': 'Description'},
            {'key': 'status', 'label': 'Status'},
        ],
    },
    {
        'file': 'LibraryMembersPage.jsx',
        'component': 'LibraryMembersPage',
        'title': 'Library members',
        'subtitle': 'Manage memberships, borrower profiles and active library access.',
        'resource': 'libraryMembers',
        'itemLabel': 'member',
        'initialValues': {'name': '', 'memberType': 'Student', 'email': '', 'status': 'Active'},
        'fields': [
            {'name': 'name', 'label': 'Member name'},
            {'name': 'memberType', 'label': 'Member type'},
            {'name': 'email', 'label': 'Email', 'type': 'email'},
            {'name': 'status', 'label': 'Status', 'type': 'select', 'options': [{'value': 'Active', 'label': 'Active'}, {'value': 'Inactive', 'label': 'Inactive'}]},
        ],
        'columns': [
            {'key': 'name', 'label': 'Name'},
            {'key': 'memberType', 'label': 'Type'},
            {'key': 'email', 'label': 'Email'},
            {'key': 'status', 'label': 'Status'},
        ],
    },
    {
        'file': 'LibraryIssuesPage.jsx',
        'component': 'LibraryIssuesPage',
        'title': 'Issue books',
        'subtitle': 'Issue books to students or staff and track due dates.',
        'resource': 'libraryIssues',
        'itemLabel': 'issue',
        'initialValues': {'bookId': '', 'memberId': '', 'dueDate': '', 'status': 'Issued'},
        'fields': [
            {'name': 'bookId', 'label': 'Book ID'},
            {'name': 'memberId', 'label': 'Member ID'},
            {'name': 'dueDate', 'label': 'Due date', 'type': 'date'},
            {'name': 'status', 'label': 'Status', 'type': 'select', 'options': [{'value': 'Issued', 'label': 'Issued'}, {'value': 'Returned', 'label': 'Returned'}]},
        ],
        'columns': [
            {'key': 'bookId', 'label': 'Book ID'},
            {'key': 'memberId', 'label': 'Member ID'},
            {'key': 'dueDate', 'label': 'Due date'},
            {'key': 'status', 'label': 'Status'},
        ],
    },
    {
        'file': 'LibraryReturnsPage.jsx',
        'component': 'LibraryReturnsPage',
        'title': 'Library returns',
        'subtitle': 'Log returned books and close circulation events.',
        'resource': 'libraryIssues',
        'itemLabel': 'return',
        'initialValues': {'bookId': '', 'memberId': '', 'returnedAt': '', 'status': 'Returned'},
        'fields': [
            {'name': 'bookId', 'label': 'Book ID'},
            {'name': 'memberId', 'label': 'Member ID'},
            {'name': 'returnedAt', 'label': 'Returned on', 'type': 'date'},
            {'name': 'status', 'label': 'Status', 'type': 'select', 'options': [{'value': 'Returned', 'label': 'Returned'}, {'value': 'Overdue', 'label': 'Overdue'}]},
        ],
        'columns': [
            {'key': 'bookId', 'label': 'Book ID'},
            {'key': 'memberId', 'label': 'Member ID'},
            {'key': 'returnedAt', 'label': 'Returned on'},
            {'key': 'status', 'label': 'Status'},
        ],
    },
    {
        'file': 'LibraryReservationsPage.jsx',
        'component': 'LibraryReservationsPage',
        'title': 'Book reservations',
        'subtitle': 'Track reservation requests and waitlist activity.',
        'resource': 'libraryReservations',
        'itemLabel': 'reservation',
        'initialValues': {'bookId': '', 'memberId': '', 'status': 'Pending'},
        'fields': [
            {'name': 'bookId', 'label': 'Book ID'},
            {'name': 'memberId', 'label': 'Member ID'},
            {'name': 'status', 'label': 'Status', 'type': 'select', 'options': [{'value': 'Pending', 'label': 'Pending'}, {'value': 'Approved', 'label': 'Approved'}, {'value': 'Cancelled', 'label': 'Cancelled'}]},
        ],
        'columns': [
            {'key': 'bookId', 'label': 'Book ID'},
            {'key': 'memberId', 'label': 'Member ID'},
            {'key': 'status', 'label': 'Status'},
        ],
    },
    {
        'file': 'LibraryRenewalsPage.jsx',
        'component': 'LibraryRenewalsPage',
        'title': 'Book renewals',
        'subtitle': 'Track renewal requests for active library loans.',
        'resource': 'libraryRenewals',
        'itemLabel': 'renewal',
        'initialValues': {'issueId': '', 'memberId': '', 'renewedOn': '', 'status': 'Pending'},
        'fields': [
            {'name': 'issueId', 'label': 'Issue ID'},
            {'name': 'memberId', 'label': 'Member ID'},
            {'name': 'renewedOn', 'label': 'Renewed on', 'type': 'date'},
            {'name': 'status', 'label': 'Status', 'type': 'select', 'options': [{'value': 'Pending', 'label': 'Pending'}, {'value': 'Approved', 'label': 'Approved'}]},
        ],
        'columns': [
            {'key': 'issueId', 'label': 'Issue ID'},
            {'key': 'memberId', 'label': 'Member ID'},
            {'key': 'renewedOn', 'label': 'Renewed on'},
            {'key': 'status', 'label': 'Status'},
        ],
    },
    {
        'file': 'LibraryFinesPage.jsx',
        'component': 'LibraryFinesPage',
        'title': 'Library fines',
        'subtitle': 'Track overdue penalties and outstanding fines.',
        'resource': 'libraryFines',
        'itemLabel': 'fine',
        'initialValues': {'memberId': '', 'amount': '', 'reason': '', 'status': 'Pending'},
        'fields': [
            {'name': 'memberId', 'label': 'Member ID'},
            {'name': 'amount', 'label': 'Amount', 'type': 'number'},
            {'name': 'reason', 'label': 'Reason'},
            {'name': 'status', 'label': 'Status', 'type': 'select', 'options': [{'value': 'Pending', 'label': 'Pending'}, {'value': 'Collected', 'label': 'Collected'}]},
        ],
        'columns': [
            {'key': 'memberId', 'label': 'Member ID'},
            {'key': 'amount', 'label': 'Amount'},
            {'key': 'reason', 'label': 'Reason'},
            {'key': 'status', 'label': 'Status'},
        ],
    },
    {
        'file': 'LibraryDamagesPage.jsx',
        'component': 'LibraryDamagesPage',
        'title': 'Damaged books',
        'subtitle': 'Log damaged library items and coordinate replacements.',
        'resource': 'libraryDamages',
        'itemLabel': 'damage record',
        'initialValues': {'bookId': '', 'reportedBy': '', 'damageType': 'Physical', 'status': 'Reported'},
        'fields': [
            {'name': 'bookId', 'label': 'Book ID'},
            {'name': 'reportedBy', 'label': 'Reported by'},
            {'name': 'damageType', 'label': 'Damage type'},
            {'name': 'status', 'label': 'Status', 'type': 'select', 'options': [{'value': 'Reported', 'label': 'Reported'}, {'value': 'Replaced', 'label': 'Replaced'}]},
        ],
        'columns': [
            {'key': 'bookId', 'label': 'Book ID'},
            {'key': 'reportedBy', 'label': 'Reported by'},
            {'key': 'damageType', 'label': 'Damage type'},
            {'key': 'status', 'label': 'Status'},
        ],
    },
    {
        'file': 'LibraryLostPage.jsx',
        'component': 'LibraryLostPage',
        'title': 'Lost books',
        'subtitle': 'Track lost books and trigger replacement workflows.',
        'resource': 'libraryLosses',
        'itemLabel': 'lost book',
        'initialValues': {'bookId': '', 'memberId': '', 'reportedAt': '', 'status': 'Lost'},
        'fields': [
            {'name': 'bookId', 'label': 'Book ID'},
            {'name': 'memberId', 'label': 'Member ID'},
            {'name': 'reportedAt', 'label': 'Reported on', 'type': 'date'},
            {'name': 'status', 'label': 'Status', 'type': 'select', 'options': [{'value': 'Lost', 'label': 'Lost'}, {'value': 'Recovered', 'label': 'Recovered'}]},
        ],
        'columns': [
            {'key': 'bookId', 'label': 'Book ID'},
            {'key': 'memberId', 'label': 'Member ID'},
            {'key': 'reportedAt', 'label': 'Reported on'},
            {'key': 'status', 'label': 'Status'},
        ],
    },
    {
        'file': 'HostelRoomsPage.jsx',
        'component': 'HostelRoomsPage',
        'title': 'Hostel rooms',
        'subtitle': 'Manage hostel rooms, beds and occupancy.',
        'resource': 'hostelRooms',
        'itemLabel': 'room',
        'initialValues': {'roomNumber': '', 'capacity': '2', 'status': 'Vacant'},
        'fields': [
            {'name': 'roomNumber', 'label': 'Room number'},
            {'name': 'capacity', 'label': 'Capacity', 'type': 'number'},
            {'name': 'status', 'label': 'Status', 'type': 'select', 'options': [{'value': 'Vacant', 'label': 'Vacant'}, {'value': 'Occupied', 'label': 'Occupied'}]},
        ],
        'columns': [
            {'key': 'roomNumber', 'label': 'Room number'},
            {'key': 'capacity', 'label': 'Capacity'},
            {'key': 'status', 'label': 'Status'},
        ],
    },
    {
        'file': 'HostelAllocationsPage.jsx',
        'component': 'HostelAllocationsPage',
        'title': 'Hostel allocations',
        'subtitle': 'Assign students to hostel rooms and monitor occupancy.',
        'resource': 'hostelAllocations',
        'itemLabel': 'allocation',
        'initialValues': {'studentId': '', 'roomId': '', 'status': 'Active'},
        'fields': [
            {'name': 'studentId', 'label': 'Student ID'},
            {'name': 'roomId', 'label': 'Room ID'},
            {'name': 'status', 'label': 'Status', 'type': 'select', 'options': [{'value': 'Active', 'label': 'Active'}, {'value': 'Transferred', 'label': 'Transferred'}]},
        ],
        'columns': [
            {'key': 'studentId', 'label': 'Student ID'},
            {'key': 'roomId', 'label': 'Room ID'},
            {'key': 'status', 'label': 'Status'},
        ],
    },
    {
        'file': 'HostelVisitorsPage.jsx',
        'component': 'HostelVisitorsPage',
        'title': 'Hostel visitors',
        'subtitle': 'Log hostel visitor entries and exit timing.',
        'resource': 'hostelVisitors',
        'itemLabel': 'visitor',
        'initialValues': {'visitorName': '', 'studentId': '', 'visitDate': '', 'status': 'Checked In'},
        'fields': [
            {'name': 'visitorName', 'label': 'Visitor name'},
            {'name': 'studentId', 'label': 'Student ID'},
            {'name': 'visitDate', 'label': 'Visit date', 'type': 'date'},
            {'name': 'status', 'label': 'Status', 'type': 'select', 'options': [{'value': 'Checked In', 'label': 'Checked In'}, {'value': 'Checked Out', 'label': 'Checked Out'}]},
        ],
        'columns': [
            {'key': 'visitorName', 'label': 'Visitor'},
            {'key': 'studentId', 'label': 'Student ID'},
            {'key': 'visitDate', 'label': 'Visit date'},
            {'key': 'status', 'label': 'Status'},
        ],
    },
    {
        'file': 'HostelComplaintsPage.jsx',
        'component': 'HostelComplaintsPage',
        'title': 'Hostel complaints',
        'subtitle': 'Capture and track hostel complaints and issue resolution.',
        'resource': 'hostelComplaints',
        'itemLabel': 'complaint',
        'initialValues': {'studentId': '', 'subject': '', 'status': 'Open'},
        'fields': [
            {'name': 'studentId', 'label': 'Student ID'},
            {'name': 'subject', 'label': 'Subject'},
            {'name': 'status', 'label': 'Status', 'type': 'select', 'options': [{'value': 'Open', 'label': 'Open'}, {'value': 'In Progress', 'label': 'In Progress'}, {'value': 'Resolved', 'label': 'Resolved'}]},
        ],
        'columns': [
            {'key': 'studentId', 'label': 'Student ID'},
            {'key': 'subject', 'label': 'Subject'},
            {'key': 'status', 'label': 'Status'},
        ],
    },
    {
        'file': 'HostelFeesPage.jsx',
        'component': 'HostelFeesPage',
        'title': 'Hostel fees',
        'subtitle': 'Capture hostel fee records and payment status.',
        'resource': 'hostelFees',
        'itemLabel': 'hostel fee',
        'initialValues': {'studentId': '', 'amount': '', 'status': 'Pending'},
        'fields': [
            {'name': 'studentId', 'label': 'Student ID'},
            {'name': 'amount', 'label': 'Amount', 'type': 'number'},
            {'name': 'status', 'label': 'Status', 'type': 'select', 'options': [{'value': 'Pending', 'label': 'Pending'}, {'value': 'Paid', 'label': 'Paid'}]},
        ],
        'columns': [
            {'key': 'studentId', 'label': 'Student ID'},
            {'key': 'amount', 'label': 'Amount'},
            {'key': 'status', 'label': 'Status'},
        ],
    },
    {
        'file': 'HostelWardensPage.jsx',
        'component': 'HostelWardensPage',
        'title': 'Hostel wardens',
        'subtitle': 'Maintain hostel warden records and assignments.',
        'resource': 'hostelWardens',
        'itemLabel': 'warden',
        'initialValues': {'name': '', 'email': '', 'phone': '', 'status': 'Active'},
        'fields': [
            {'name': 'name', 'label': 'Name'},
            {'name': 'email', 'label': 'Email', 'type': 'email'},
            {'name': 'phone', 'label': 'Phone'},
            {'name': 'status', 'label': 'Status', 'type': 'select', 'options': [{'value': 'Active', 'label': 'Active'}, {'value': 'Inactive', 'label': 'Inactive'}]},
        ],
        'columns': [
            {'key': 'name', 'label': 'Name'},
            {'key': 'email', 'label': 'Email'},
            {'key': 'phone', 'label': 'Phone'},
            {'key': 'status', 'label': 'Status'},
        ],
    },
    {
        'file': 'HostelMaintenancePage.jsx',
        'component': 'HostelMaintenancePage',
        'title': 'Hostel maintenance',
        'subtitle': 'Track hostel maintenance requests and asset upkeep.',
        'resource': 'maintenanceRequests',
        'itemLabel': 'maintenance request',
        'initialValues': {'roomId': '', 'subject': '', 'priority': 'Medium', 'status': 'Open'},
        'fields': [
            {'name': 'roomId', 'label': 'Room ID'},
            {'name': 'subject', 'label': 'Subject'},
            {'name': 'priority', 'label': 'Priority'},
            {'name': 'status', 'label': 'Status', 'type': 'select', 'options': [{'value': 'Open', 'label': 'Open'}, {'value': 'Closed', 'label': 'Closed'}]},
        ],
        'columns': [
            {'key': 'roomId', 'label': 'Room ID'},
            {'key': 'subject', 'label': 'Subject'},
            {'key': 'priority', 'label': 'Priority'},
            {'key': 'status', 'label': 'Status'},
        ],
    },
    {
        'file': 'TransportVehiclesPage.jsx',
        'component': 'TransportVehiclesPage',
        'title': 'Transport vehicles',
        'subtitle': 'Manage vehicle inventory and service readiness.',
        'resource': 'transportVehicles',
        'itemLabel': 'vehicle',
        'initialValues': {'name': '', 'registrationNumber': '', 'status': 'Active'},
        'fields': [
            {'name': 'name', 'label': 'Vehicle name'},
            {'name': 'registrationNumber', 'label': 'Registration number'},
            {'name': 'status', 'label': 'Status', 'type': 'select', 'options': [{'value': 'Active', 'label': 'Active'}, {'value': 'Inactive', 'label': 'Inactive'}]},
        ],
        'columns': [
            {'key': 'name', 'label': 'Vehicle'},
            {'key': 'registrationNumber', 'label': 'Registration number'},
            {'key': 'status', 'label': 'Status'},
        ],
    },
    {
        'file': 'TransportDriversPage.jsx',
        'component': 'TransportDriversPage',
        'title': 'Transport drivers',
        'subtitle': 'Track driver records and assignment status.',
        'resource': 'transportDrivers',
        'itemLabel': 'driver',
        'initialValues': {'name': '', 'phone': '', 'status': 'Active'},
        'fields': [
            {'name': 'name', 'label': 'Driver name'},
            {'name': 'phone', 'label': 'Phone'},
            {'name': 'status', 'label': 'Status', 'type': 'select', 'options': [{'value': 'Active', 'label': 'Active'}, {'value': 'Inactive', 'label': 'Inactive'}]},
        ],
        'columns': [
            {'key': 'name', 'label': 'Driver'},
            {'key': 'phone', 'label': 'Phone'},
            {'key': 'status', 'label': 'Status'},
        ],
    },
    {
        'file': 'TransportConductorsPage.jsx',
        'component': 'TransportConductorsPage',
        'title': 'Transport conductors',
        'subtitle': 'Manage conductor assignments and support staff details.',
        'resource': 'transportConductors',
        'itemLabel': 'conductor',
        'initialValues': {'name': '', 'phone': '', 'status': 'Active'},
        'fields': [
            {'name': 'name', 'label': 'Conductor name'},
            {'name': 'phone', 'label': 'Phone'},
            {'name': 'status', 'label': 'Status', 'type': 'select', 'options': [{'value': 'Active', 'label': 'Active'}, {'value': 'Inactive', 'label': 'Inactive'}]},
        ],
        'columns': [
            {'key': 'name', 'label': 'Conductor'},
            {'key': 'phone', 'label': 'Phone'},
            {'key': 'status', 'label': 'Status'},
        ],
    },
    {
        'file': 'TransportRoutesPage.jsx',
        'component': 'TransportRoutesPage',
        'title': 'Transport routes',
        'subtitle': 'Plan routes and keep route details up to date.',
        'resource': 'transportRoutes',
        'itemLabel': 'route',
        'initialValues': {'name': '', 'startPoint': '', 'endPoint': '', 'status': 'Active'},
        'fields': [
            {'name': 'name', 'label': 'Route name'},
            {'name': 'startPoint', 'label': 'Start point'},
            {'name': 'endPoint', 'label': 'End point'},
            {'name': 'status', 'label': 'Status', 'type': 'select', 'options': [{'value': 'Active', 'label': 'Active'}, {'value': 'Inactive', 'label': 'Inactive'}]},
        ],
        'columns': [
            {'key': 'name', 'label': 'Route'},
            {'key': 'startPoint', 'label': 'Start point'},
            {'key': 'endPoint', 'label': 'End point'},
            {'key': 'status', 'label': 'Status'},
        ],
    },
    {
        'file': 'TransportStopsPage.jsx',
        'component': 'TransportStopsPage',
        'title': 'Transport stops',
        'subtitle': 'Store route stops and pickup drop-off locations.',
        'resource': 'transportStops',
        'itemLabel': 'stop',
        'initialValues': {'name': '', 'routeId': '', 'status': 'Active'},
        'fields': [
            {'name': 'name', 'label': 'Stop name'},
            {'name': 'routeId', 'label': 'Route ID'},
            {'name': 'status', 'label': 'Status', 'type': 'select', 'options': [{'value': 'Active', 'label': 'Active'}, {'value': 'Inactive', 'label': 'Inactive'}]},
        ],
        'columns': [
            {'key': 'name', 'label': 'Stop'},
            {'key': 'routeId', 'label': 'Route ID'},
            {'key': 'status', 'label': 'Status'},
        ],
    },
    {
        'file': 'TransportStudentAssignmentsPage.jsx',
        'component': 'TransportStudentAssignmentsPage',
        'title': 'Student transport assignments',
        'subtitle': 'Assign students to transport routes and pickups.',
        'resource': 'studentTransportAssignments',
        'itemLabel': 'assignment',
        'initialValues': {'studentId': '', 'routeId': '', 'status': 'Active'},
        'fields': [
            {'name': 'studentId', 'label': 'Student ID'},
            {'name': 'routeId', 'label': 'Route ID'},
            {'name': 'status', 'label': 'Status', 'type': 'select', 'options': [{'value': 'Active', 'label': 'Active'}, {'value': 'Inactive', 'label': 'Inactive'}]},
        ],
        'columns': [
            {'key': 'studentId', 'label': 'Student ID'},
            {'key': 'routeId', 'label': 'Route ID'},
            {'key': 'status', 'label': 'Status'},
        ],
    },
    {
        'file': 'TransportEmployeeAssignmentsPage.jsx',
        'component': 'TransportEmployeeAssignmentsPage',
        'title': 'Employee transport assignments',
        'subtitle': 'Track transport assignments for staff and employees.',
        'resource': 'employeeTransportAssignments',
        'itemLabel': 'assignment',
        'initialValues': {'employeeId': '', 'routeId': '', 'status': 'Active'},
        'fields': [
            {'name': 'employeeId', 'label': 'Employee ID'},
            {'name': 'routeId', 'label': 'Route ID'},
            {'name': 'status', 'label': 'Status', 'type': 'select', 'options': [{'value': 'Active', 'label': 'Active'}, {'value': 'Inactive', 'label': 'Inactive'}]},
        ],
        'columns': [
            {'key': 'employeeId', 'label': 'Employee ID'},
            {'key': 'routeId', 'label': 'Route ID'},
            {'key': 'status', 'label': 'Status'},
        ],
    },
    {
        'file': 'TransportFuelPage.jsx',
        'component': 'TransportFuelPage',
        'title': 'Fuel entries',
        'subtitle': 'Record fuel consumption for each transport vehicle.',
        'resource': 'fuelEntries',
        'itemLabel': 'fuel entry',
        'initialValues': {'vehicleId': '', 'quantity': '', 'date': '', 'status': 'Recorded'},
        'fields': [
            {'name': 'vehicleId', 'label': 'Vehicle ID'},
            {'name': 'quantity', 'label': 'Quantity', 'type': 'number'},
            {'name': 'date', 'label': 'Date', 'type': 'date'},
            {'name': 'status', 'label': 'Status', 'type': 'select', 'options': [{'value': 'Recorded', 'label': 'Recorded'}, {'value': 'Approved', 'label': 'Approved'}]},
        ],
        'columns': [
            {'key': 'vehicleId', 'label': 'Vehicle ID'},
            {'key': 'quantity', 'label': 'Quantity'},
            {'key': 'date', 'label': 'Date'},
            {'key': 'status', 'label': 'Status'},
        ],
    },
    {
        'file': 'TransportMaintenancePage.jsx',
        'component': 'TransportMaintenancePage',
        'title': 'Transport maintenance',
        'subtitle': 'Track repairs and preventive maintenance for vehicles.',
        'resource': 'maintenanceRecords',
        'itemLabel': 'maintenance record',
        'initialValues': {'vehicleId': '', 'serviceType': '', 'status': 'Scheduled'},
        'fields': [
            {'name': 'vehicleId', 'label': 'Vehicle ID'},
            {'name': 'serviceType', 'label': 'Service type'},
            {'name': 'status', 'label': 'Status', 'type': 'select', 'options': [{'value': 'Scheduled', 'label': 'Scheduled'}, {'value': 'Completed', 'label': 'Completed'}]},
        ],
        'columns': [
            {'key': 'vehicleId', 'label': 'Vehicle ID'},
            {'key': 'serviceType', 'label': 'Service type'},
            {'key': 'status', 'label': 'Status'},
        ],
    },
    {
        'file': 'FeeCollectionPage.jsx',
        'component': 'FeeCollectionPage',
        'title': 'Fee collection',
        'subtitle': 'Collect student fees and view outstanding balances.',
        'resource': 'feePayments',
        'itemLabel': 'fee collection',
        'initialValues': {'studentId': '', 'amount': '', 'paymentDate': '', 'status': 'Paid'},
        'fields': [
            {'name': 'studentId', 'label': 'Student ID'},
            {'name': 'amount', 'label': 'Amount', 'type': 'number'},
            {'name': 'paymentDate', 'label': 'Payment date', 'type': 'date'},
            {'name': 'status', 'label': 'Status', 'type': 'select', 'options': [{'value': 'Paid', 'label': 'Paid'}, {'value': 'Pending', 'label': 'Pending'}]},
        ],
        'columns': [
            {'key': 'studentId', 'label': 'Student ID'},
            {'key': 'amount', 'label': 'Amount'},
            {'key': 'paymentDate', 'label': 'Payment date'},
            {'key': 'status', 'label': 'Status'},
        ],
    },
    {
        'file': 'ScholarshipsPage.jsx',
        'component': 'ScholarshipsPage',
        'title': 'Scholarships',
        'subtitle': 'Manage scholarship programmes and disbursements.',
        'resource': 'scholarships',
        'itemLabel': 'scholarship',
        'initialValues': {'name': '', 'studentId': '', 'amount': '', 'status': 'Approved'},
        'fields': [
            {'name': 'name', 'label': 'Scholarship name'},
            {'name': 'studentId', 'label': 'Student ID'},
            {'name': 'amount', 'label': 'Amount', 'type': 'number'},
            {'name': 'status', 'label': 'Status', 'type': 'select', 'options': [{'value': 'Approved', 'label': 'Approved'}, {'value': 'Pending', 'label': 'Pending'}]},
        ],
        'columns': [
            {'key': 'name', 'label': 'Scholarship'},
            {'key': 'studentId', 'label': 'Student ID'},
            {'key': 'amount', 'label': 'Amount'},
            {'key': 'status', 'label': 'Status'},
        ],
    },
    {
        'file': 'PaymentsPage.jsx',
        'component': 'PaymentsPage',
        'title': 'Payments',
        'subtitle': 'Record and review business payments and settlements.',
        'resource': 'payments',
        'itemLabel': 'payment',
        'initialValues': {'reference': '', 'amount': '', 'status': 'Pending'},
        'fields': [
            {'name': 'reference', 'label': 'Payment reference'},
            {'name': 'amount', 'label': 'Amount', 'type': 'number'},
            {'name': 'status', 'label': 'Status', 'type': 'select', 'options': [{'value': 'Pending', 'label': 'Pending'}, {'value': 'Completed', 'label': 'Completed'}]},
        ],
        'columns': [
            {'key': 'reference', 'label': 'Reference'},
            {'key': 'amount', 'label': 'Amount'},
            {'key': 'status', 'label': 'Status'},
        ],
    },
    {
        'file': 'ReceiptsPage.jsx',
        'component': 'ReceiptsPage',
        'title': 'Receipts',
        'subtitle': 'Generate and track official receipts.',
        'resource': 'receipts',
        'itemLabel': 'receipt',
        'initialValues': {'receiptNumber': '', 'amount': '', 'status': 'Issued'},
        'fields': [
            {'name': 'receiptNumber', 'label': 'Receipt number'},
            {'name': 'amount', 'label': 'Amount', 'type': 'number'},
            {'name': 'status', 'label': 'Status', 'type': 'select', 'options': [{'value': 'Issued', 'label': 'Issued'}, {'value': 'Cancelled', 'label': 'Cancelled'}]},
        ],
        'columns': [
            {'key': 'receiptNumber', 'label': 'Receipt'},
            {'key': 'amount', 'label': 'Amount'},
            {'key': 'status', 'label': 'Status'},
        ],
    },
    {
        'file': 'AccountsPage.jsx',
        'component': 'AccountsPage',
        'title': 'Chart of accounts',
        'subtitle': 'Maintain account categories and ledger structures.',
        'resource': 'accounts',
        'itemLabel': 'account',
        'initialValues': {'name': '', 'accountType': 'Asset', 'status': 'Active'},
        'fields': [
            {'name': 'name', 'label': 'Account name'},
            {'name': 'accountType', 'label': 'Account type'},
            {'name': 'status', 'label': 'Status', 'type': 'select', 'options': [{'value': 'Active', 'label': 'Active'}, {'value': 'Inactive', 'label': 'Inactive'}]},
        ],
        'columns': [
            {'key': 'name', 'label': 'Account'},
            {'key': 'accountType', 'label': 'Type'},
            {'key': 'status', 'label': 'Status'},
        ],
    },
    {
        'file': 'IncomePage.jsx',
        'component': 'IncomePage',
        'title': 'Income entries',
        'subtitle': 'Track recurring and one-off income entries.',
        'resource': 'accounts',
        'itemLabel': 'income entry',
        'initialValues': {'name': '', 'amount': '', 'date': '', 'status': 'Recorded'},
        'fields': [
            {'name': 'name', 'label': 'Entry name'},
            {'name': 'amount', 'label': 'Amount', 'type': 'number'},
            {'name': 'date', 'label': 'Date', 'type': 'date'},
            {'name': 'status', 'label': 'Status', 'type': 'select', 'options': [{'value': 'Recorded', 'label': 'Recorded'}, {'value': 'Approved', 'label': 'Approved'}]},
        ],
        'columns': [
            {'key': 'name', 'label': 'Entry'},
            {'key': 'amount', 'label': 'Amount'},
            {'key': 'date', 'label': 'Date'},
            {'key': 'status', 'label': 'Status'},
        ],
    },
    {
        'file': 'ExpensesPage.jsx',
        'component': 'ExpensesPage',
        'title': 'Expenses',
        'subtitle': 'Track operational expenses and approvals.',
        'resource': 'accounts',
        'itemLabel': 'expense',
        'initialValues': {'name': '', 'amount': '', 'date': '', 'status': 'Pending'},
        'fields': [
            {'name': 'name', 'label': 'Expense name'},
            {'name': 'amount', 'label': 'Amount', 'type': 'number'},
            {'name': 'date', 'label': 'Date', 'type': 'date'},
            {'name': 'status', 'label': 'Status', 'type': 'select', 'options': [{'value': 'Pending', 'label': 'Pending'}, {'value': 'Approved', 'label': 'Approved'}]},
        ],
        'columns': [
            {'key': 'name', 'label': 'Expense'},
            {'key': 'amount', 'label': 'Amount'},
            {'key': 'date', 'label': 'Date'},
            {'key': 'status', 'label': 'Status'},
        ],
    },
    {
        'file': 'AssetsPage.jsx',
        'component': 'AssetsPage',
        'title': 'Assets',
        'subtitle': 'Manage the asset register and current usage.',
        'resource': 'assets',
        'itemLabel': 'asset',
        'initialValues': {'name': '', 'category': '', 'status': 'Active'},
        'fields': [
            {'name': 'name', 'label': 'Asset name'},
            {'name': 'category', 'label': 'Category'},
            {'name': 'status', 'label': 'Status', 'type': 'select', 'options': [{'value': 'Active', 'label': 'Active'}, {'value': 'Retired', 'label': 'Retired'}]},
        ],
        'columns': [
            {'key': 'name', 'label': 'Asset'},
            {'key': 'category', 'label': 'Category'},
            {'key': 'status', 'label': 'Status'},
        ],
    },
    {
        'file': 'AssetCategoriesPage.jsx',
        'component': 'AssetCategoriesPage',
        'title': 'Asset categories',
        'subtitle': 'Organize asset inventory by category.',
        'resource': 'assetCategories',
        'itemLabel': 'asset category',
        'initialValues': {'name': '', 'status': 'Active'},
        'fields': [
            {'name': 'name', 'label': 'Category name'},
            {'name': 'status', 'label': 'Status', 'type': 'select', 'options': [{'value': 'Active', 'label': 'Active'}, {'value': 'Inactive', 'label': 'Inactive'}]},
        ],
        'columns': [
            {'key': 'name', 'label': 'Category'},
            {'key': 'status', 'label': 'Status'},
        ],
    },
    {
        'file': 'StockPage.jsx',
        'component': 'StockPage',
        'title': 'Inventory stock',
        'subtitle': 'Monitor stock levels and replenishment status.',
        'resource': 'stockMovements',
        'itemLabel': 'stock item',
        'initialValues': {'itemName': '', 'quantity': '', 'status': 'In Stock'},
        'fields': [
            {'name': 'itemName', 'label': 'Item name'},
            {'name': 'quantity', 'label': 'Quantity', 'type': 'number'},
            {'name': 'status', 'label': 'Status', 'type': 'select', 'options': [{'value': 'In Stock', 'label': 'In Stock'}, {'value': 'Low Stock', 'label': 'Low Stock'}]},
        ],
        'columns': [
            {'key': 'itemName', 'label': 'Item'},
            {'key': 'quantity', 'label': 'Quantity'},
            {'key': 'status', 'label': 'Status'},
        ],
    },
    {
        'file': 'VendorsPage.jsx',
        'component': 'VendorsPage',
        'title': 'Vendors',
        'subtitle': 'Track supplier records and procurement relationships.',
        'resource': 'vendors',
        'itemLabel': 'vendor',
        'initialValues': {'name': '', 'email': '', 'phone': '', 'status': 'Active'},
        'fields': [
            {'name': 'name', 'label': 'Vendor name'},
            {'name': 'email', 'label': 'Email', 'type': 'email'},
            {'name': 'phone', 'label': 'Phone'},
            {'name': 'status', 'label': 'Status', 'type': 'select', 'options': [{'value': 'Active', 'label': 'Active'}, {'value': 'Inactive', 'label': 'Inactive'}]},
        ],
        'columns': [
            {'key': 'name', 'label': 'Vendor'},
            {'key': 'email', 'label': 'Email'},
            {'key': 'phone', 'label': 'Phone'},
            {'key': 'status', 'label': 'Status'},
        ],
    },
    {
        'file': 'PurchaseOrdersPage.jsx',
        'component': 'PurchaseOrdersPage',
        'title': 'Purchase orders',
        'subtitle': 'Manage purchasing requests and approvals.',
        'resource': 'purchaseOrders',
        'itemLabel': 'purchase order',
        'initialValues': {'orderNumber': '', 'vendorName': '', 'status': 'Draft'},
        'fields': [
            {'name': 'orderNumber', 'label': 'Order number'},
            {'name': 'vendorName', 'label': 'Vendor'},
            {'name': 'status', 'label': 'Status', 'type': 'select', 'options': [{'value': 'Draft', 'label': 'Draft'}, {'value': 'Approved', 'label': 'Approved'}]},
        ],
        'columns': [
            {'key': 'orderNumber', 'label': 'Order'},
            {'key': 'vendorName', 'label': 'Vendor'},
            {'key': 'status', 'label': 'Status'},
        ],
    },
    {
        'file': 'GoodsReceiptsPage.jsx',
        'component': 'GoodsReceiptsPage',
        'title': 'Goods receipts',
        'subtitle': 'Track received inventory and deliveries.',
        'resource': 'purchaseOrders',
        'itemLabel': 'goods receipt',
        'initialValues': {'receiptNumber': '', 'vendorName': '', 'status': 'Received'},
        'fields': [
            {'name': 'receiptNumber', 'label': 'Receipt number'},
            {'name': 'vendorName', 'label': 'Vendor'},
            {'name': 'status', 'label': 'Status', 'type': 'select', 'options': [{'value': 'Received', 'label': 'Received'}, {'value': 'Pending', 'label': 'Pending'}]},
        ],
        'columns': [
            {'key': 'receiptNumber', 'label': 'Receipt'},
            {'key': 'vendorName', 'label': 'Vendor'},
            {'key': 'status', 'label': 'Status'},
        ],
    },
    {
        'file': 'AssetAssignmentsPage.jsx',
        'component': 'AssetAssignmentsPage',
        'title': 'Asset assignments',
        'subtitle': 'Assign assets to departments and employees.',
        'resource': 'assetAssignments',
        'itemLabel': 'asset assignment',
        'initialValues': {'assetId': '', 'assignedTo': '', 'status': 'Assigned'},
        'fields': [
            {'name': 'assetId', 'label': 'Asset ID'},
            {'name': 'assignedTo', 'label': 'Assigned to'},
            {'name': 'status', 'label': 'Status', 'type': 'select', 'options': [{'value': 'Assigned', 'label': 'Assigned'}, {'value': 'Returned', 'label': 'Returned'}]},
        ],
        'columns': [
            {'key': 'assetId', 'label': 'Asset ID'},
            {'key': 'assignedTo', 'label': 'Assigned to'},
            {'key': 'status', 'label': 'Status'},
        ],
    },
    {
        'file': 'CounsellingPage.jsx',
        'component': 'CounsellingPage',
        'title': 'Counselling sessions',
        'subtitle': 'Track student counselling sessions and outcomes.',
        'resource': 'students',
        'itemLabel': 'counselling session',
        'initialValues': {'studentName': '', 'counsellor': '', 'status': 'Scheduled'},
        'fields': [
            {'name': 'studentName', 'label': 'Student name'},
            {'name': 'counsellor', 'label': 'Counsellor'},
            {'name': 'status', 'label': 'Status', 'type': 'select', 'options': [{'value': 'Scheduled', 'label': 'Scheduled'}, {'value': 'Completed', 'label': 'Completed'}]},
        ],
        'columns': [
            {'key': 'studentName', 'label': 'Student'},
            {'key': 'counsellor', 'label': 'Counsellor'},
            {'key': 'status', 'label': 'Status'},
        ],
    },
    {
        'file': 'MarketingPage.jsx',
        'component': 'MarketingPage',
        'title': 'Marketing campaigns',
        'subtitle': 'Coordinate campaigns and outreach activity.',
        'resource': 'leads',
        'itemLabel': 'campaign',
        'initialValues': {'name': '', 'channel': 'Email', 'status': 'Planned'},
        'fields': [
            {'name': 'name', 'label': 'Campaign name'},
            {'name': 'channel', 'label': 'Channel'},
            {'name': 'status', 'label': 'Status', 'type': 'select', 'options': [{'value': 'Planned', 'label': 'Planned'}, {'value': 'Running', 'label': 'Running'}, {'value': 'Completed', 'label': 'Completed'}]},
        ],
        'columns': [
            {'key': 'name', 'label': 'Campaign'},
            {'key': 'channel', 'label': 'Channel'},
            {'key': 'status', 'label': 'Status'},
        ],
    },
    {
        'file': 'CampaignsPage.jsx',
        'component': 'CampaignsPage',
        'title': 'CRM campaigns',
        'subtitle': 'Review outreach campaigns and promoter activity.',
        'resource': 'leads',
        'itemLabel': 'campaign',
        'initialValues': {'name': '', 'priority': 'Medium', 'status': 'Active'},
        'fields': [
            {'name': 'name', 'label': 'Campaign name'},
            {'name': 'priority', 'label': 'Priority'},
            {'name': 'status', 'label': 'Status', 'type': 'select', 'options': [{'value': 'Active', 'label': 'Active'}, {'value': 'Paused', 'label': 'Paused'}]},
        ],
        'columns': [
            {'key': 'name', 'label': 'Campaign'},
            {'key': 'priority', 'label': 'Priority'},
            {'key': 'status', 'label': 'Status'},
        ],
    },
    {
        'file': 'LMSCoursesPage.jsx',
        'component': 'LMSCoursesPage',
        'title': 'LMS courses',
        'subtitle': 'Maintain learning content and course catalogues.',
        'resource': 'courses',
        'itemLabel': 'course',
        'initialValues': {'name': '', 'category': 'General', 'status': 'Draft'},
        'fields': [
            {'name': 'name', 'label': 'Course name'},
            {'name': 'category', 'label': 'Category'},
            {'name': 'status', 'label': 'Status', 'type': 'select', 'options': [{'value': 'Draft', 'label': 'Draft'}, {'value': 'Published', 'label': 'Published'}]},
        ],
        'columns': [
            {'key': 'name', 'label': 'Course'},
            {'key': 'category', 'label': 'Category'},
            {'key': 'status', 'label': 'Status'},
        ],
    },
    {
        'file': 'StudyMaterialPage.jsx',
        'component': 'StudyMaterialPage',
        'title': 'Study material',
        'subtitle': 'Publish notes and lessons for LMS learners.',
        'resource': 'courses',
        'itemLabel': 'study material',
        'initialValues': {'title': '', 'topic': '', 'status': 'Draft'},
        'fields': [
            {'name': 'title', 'label': 'Title'},
            {'name': 'topic', 'label': 'Topic'},
            {'name': 'status', 'label': 'Status', 'type': 'select', 'options': [{'value': 'Draft', 'label': 'Draft'}, {'value': 'Published', 'label': 'Published'}]},
        ],
        'columns': [
            {'key': 'title', 'label': 'Title'},
            {'key': 'topic', 'label': 'Topic'},
            {'key': 'status', 'label': 'Status'},
        ],
    },
    {
        'file': 'VideoLecturesPage.jsx',
        'component': 'VideoLecturesPage',
        'title': 'Video lectures',
        'subtitle': 'Manage recorded lectures and embedded video links.',
        'resource': 'courses',
        'itemLabel': 'video lecture',
        'initialValues': {'title': '', 'url': '', 'status': 'Draft'},
        'fields': [
            {'name': 'title', 'label': 'Title'},
            {'name': 'url', 'label': 'Video URL', 'type': 'url'},
            {'name': 'status', 'label': 'Status', 'type': 'select', 'options': [{'value': 'Draft', 'label': 'Draft'}, {'value': 'Published', 'label': 'Published'}]},
        ],
        'columns': [
            {'key': 'title', 'label': 'Title'},
            {'key': 'url', 'label': 'URL'},
            {'key': 'status', 'label': 'Status'},
        ],
    },
    {
        'file': 'OnlineTestsPage.jsx',
        'component': 'OnlineTestsPage',
        'title': 'Online tests',
        'subtitle': 'Create and administer online assessments.',
        'resource': 'courses',
        'itemLabel': 'online test',
        'initialValues': {'title': '', 'duration': '60', 'status': 'Draft'},
        'fields': [
            {'name': 'title', 'label': 'Test title'},
            {'name': 'duration', 'label': 'Duration (mins)', 'type': 'number'},
            {'name': 'status', 'label': 'Status', 'type': 'select', 'options': [{'value': 'Draft', 'label': 'Draft'}, {'value': 'Published', 'label': 'Published'}]},
        ],
        'columns': [
            {'key': 'title', 'label': 'Title'},
            {'key': 'duration', 'label': 'Duration'},
            {'key': 'status', 'label': 'Status'},
        ],
    },
    {
        'file': 'LMSCertificatesPage.jsx',
        'component': 'LMSCertificatesPage',
        'title': 'LMS certificates',
        'subtitle': 'Issue completion certificates for course learners.',
        'resource': 'courses',
        'itemLabel': 'certificate',
        'initialValues': {'learnerName': '', 'courseName': '', 'status': 'Issued'},
        'fields': [
            {'name': 'learnerName', 'label': 'Learner name'},
            {'name': 'courseName', 'label': 'Course name'},
            {'name': 'status', 'label': 'Status', 'type': 'select', 'options': [{'value': 'Issued', 'label': 'Issued'}, {'value': 'Pending', 'label': 'Pending'}]},
        ],
        'columns': [
            {'key': 'learnerName', 'label': 'Learner'},
            {'key': 'courseName', 'label': 'Course'},
            {'key': 'status', 'label': 'Status'},
        ],
    },
    {
        'file': 'SecurityVisitorsPage.jsx',
        'component': 'SecurityVisitorsPage',
        'title': 'Security visitors',
        'subtitle': 'Track visitor access and security clearance.',
        'resource': 'visitors',
        'itemLabel': 'visitor',
        'initialValues': {'name': '', 'purpose': '', 'status': 'Checked In'},
        'fields': [
            {'name': 'name', 'label': 'Visitor name'},
            {'name': 'purpose', 'label': 'Purpose'},
            {'name': 'status', 'label': 'Status', 'type': 'select', 'options': [{'value': 'Checked In', 'label': 'Checked In'}, {'value': 'Checked Out', 'label': 'Checked Out'}]},
        ],
        'columns': [
            {'key': 'name', 'label': 'Visitor'},
            {'key': 'purpose', 'label': 'Purpose'},
            {'key': 'status', 'label': 'Status'},
        ],
    },
    {
        'file': 'GatePassPage.jsx',
        'component': 'GatePassPage',
        'title': 'Gate pass',
        'subtitle': 'Issue temporary gate passes for approved entry.',
        'resource': 'gatePasses',
        'itemLabel': 'gate pass',
        'initialValues': {'name': '', 'reason': '', 'status': 'Active'},
        'fields': [
            {'name': 'name', 'label': 'Person name'},
            {'name': 'reason', 'label': 'Reason'},
            {'name': 'status', 'label': 'Status', 'type': 'select', 'options': [{'value': 'Active', 'label': 'Active'}, {'value': 'Expired', 'label': 'Expired'}]},
        ],
        'columns': [
            {'key': 'name', 'label': 'Person'},
            {'key': 'reason', 'label': 'Reason'},
            {'key': 'status', 'label': 'Status'},
        ],
    },
    {
        'file': 'IncidentsPage.jsx',
        'component': 'IncidentsPage',
        'title': 'Security incidents',
        'subtitle': 'Record security incidents and follow-up actions.',
        'resource': 'incidents',
        'itemLabel': 'incident',
        'initialValues': {'title': '', 'severity': 'Medium', 'status': 'Open'},
        'fields': [
            {'name': 'title', 'label': 'Incident title'},
            {'name': 'severity', 'label': 'Severity'},
            {'name': 'status', 'label': 'Status', 'type': 'select', 'options': [{'value': 'Open', 'label': 'Open'}, {'value': 'Resolved', 'label': 'Resolved'}]},
        ],
        'columns': [
            {'key': 'title', 'label': 'Incident'},
            {'key': 'severity', 'label': 'Severity'},
            {'key': 'status', 'label': 'Status'},
        ],
    },
    {
        'file': 'EnquiriesPage.jsx',
        'component': 'EnquiriesPage',
        'title': 'Admissions enquiries',
        'subtitle': 'Track admission enquiries and follow-up actions.',
        'resource': 'leads',
        'itemLabel': 'enquiry',
        'initialValues': {'name': '', 'phone': '', 'status': 'New'},
        'fields': [
            {'name': 'name', 'label': 'Name'},
            {'name': 'phone', 'label': 'Phone'},
            {'name': 'status', 'label': 'Status', 'type': 'select', 'options': [{'value': 'New', 'label': 'New'}, {'value': 'Follow Up', 'label': 'Follow Up'}, {'value': 'Converted', 'label': 'Converted'}]},
        ],
        'columns': [
            {'key': 'name', 'label': 'Name'},
            {'key': 'phone', 'label': 'Phone'},
            {'key': 'status', 'label': 'Status'},
        ],
    },
    {
        'file': 'AdmissionCounsellingPage.jsx',
        'component': 'AdmissionCounsellingPage',
        'title': 'Admission counselling',
        'subtitle': 'Track admission counselling calls and meetings.',
        'resource': 'leads',
        'itemLabel': 'counselling entry',
        'initialValues': {'name': '', 'counsellor': '', 'status': 'Scheduled'},
        'fields': [
            {'name': 'name', 'label': 'Student name'},
            {'name': 'counsellor', 'label': 'Counsellor'},
            {'name': 'status', 'label': 'Status', 'type': 'select', 'options': [{'value': 'Scheduled', 'label': 'Scheduled'}, {'value': 'Completed', 'label': 'Completed'}]},
        ],
        'columns': [
            {'key': 'name', 'label': 'Student'},
            {'key': 'counsellor', 'label': 'Counsellor'},
            {'key': 'status', 'label': 'Status'},
        ],
    },
    {
        'file': 'ApplicationsPage.jsx',
        'component': 'ApplicationsPage',
        'title': 'Admission applications',
        'subtitle': 'Review admission applications and their current stage.',
        'resource': 'leads',
        'itemLabel': 'application',
        'initialValues': {'name': '', 'program': '', 'status': 'Submitted'},
        'fields': [
            {'name': 'name', 'label': 'Applicant name'},
            {'name': 'program', 'label': 'Program'},
            {'name': 'status', 'label': 'Status', 'type': 'select', 'options': [{'value': 'Submitted', 'label': 'Submitted'}, {'value': 'Shortlisted', 'label': 'Shortlisted'}, {'value': 'Admitted', 'label': 'Admitted'}]},
        ],
        'columns': [
            {'key': 'name', 'label': 'Applicant'},
            {'key': 'program', 'label': 'Program'},
            {'key': 'status', 'label': 'Status'},
        ],
    },
    {
        'file': 'ParentsPage.jsx',
        'component': 'ParentsPage',
        'title': 'Parents & guardians',
        'subtitle': 'Review parent and guardian information linked to student records.',
        'resource': 'students',
        'itemLabel': 'parent',
        'initialValues': {'name': '', 'guardianName': '', 'guardianMobile': '', 'status': 'Active'},
        'fields': [
            {'name': 'name', 'label': 'Student name'},
            {'name': 'guardianName', 'label': 'Guardian name'},
            {'name': 'guardianMobile', 'label': 'Guardian mobile'},
            {'name': 'status', 'label': 'Status', 'type': 'select', 'options': [{'value': 'Active', 'label': 'Active'}, {'value': 'Inactive', 'label': 'Inactive'}]},
        ],
        'columns': [
            {'key': 'name', 'label': 'Student'},
            {'key': 'guardianName', 'label': 'Guardian'},
            {'key': 'guardianMobile', 'label': 'Guardian mobile'},
            {'key': 'status', 'label': 'Status'},
        ],
    },
    {
        'file': 'AnalyticsPage.jsx',
        'component': 'AnalyticsPage',
        'title': 'Analytics',
        'subtitle': 'Review KPI widgets and operational metrics.',
        'resource': 'reports',
        'itemLabel': 'analytics insight',
        'initialValues': {'title': '', 'category': 'Performance', 'status': 'Published'},
        'fields': [
            {'name': 'title', 'label': 'Insight title'},
            {'name': 'category', 'label': 'Category'},
            {'name': 'status', 'label': 'Status', 'type': 'select', 'options': [{'value': 'Published', 'label': 'Published'}, {'value': 'Draft', 'label': 'Draft'}]},
        ],
        'columns': [
            {'key': 'title', 'label': 'Insight'},
            {'key': 'category', 'label': 'Category'},
            {'key': 'status', 'label': 'Status'},
        ],
    },
    {
        'file': 'NotificationsPage.jsx',
        'component': 'NotificationsPage',
        'title': 'Notifications',
        'subtitle': 'Monitor institutional alerts and communications.',
        'resource': 'students',
        'itemLabel': 'notification',
        'initialValues': {'title': '', 'channel': 'System', 'status': 'Sent'},
        'fields': [
            {'name': 'title', 'label': 'Title'},
            {'name': 'channel', 'label': 'Channel'},
            {'name': 'status', 'label': 'Status', 'type': 'select', 'options': [{'value': 'Sent', 'label': 'Sent'}, {'value': 'Scheduled', 'label': 'Scheduled'}]},
        ],
        'columns': [
            {'key': 'title', 'label': 'Title'},
            {'key': 'channel', 'label': 'Channel'},
            {'key': 'status', 'label': 'Status'},
        ],
    },
]

for page in pages:
    fields_json = json.dumps(page['fields'])
    columns_json = json.dumps(page['columns'])
    initial_values_json = json.dumps(page['initialValues'])

    content = (
        "import GenericCrudPage from '../components/ui/GenericCrudPage.jsx';\n\n"
        f"const fields = {fields_json};\n"
        f"const columns = {columns_json};\n\n"
        f"export default function {page['component']}() {{\n"
        "  return (\n"
        "    <GenericCrudPage\n"
        f'      title="{page["title"]}"\n'
        f'      subtitle="{page["subtitle"]}"\n'
        f'      resource="{page["resource"]}"\n'
        f'      itemLabel="{page["itemLabel"]}"\n'
        f"      initialValues={{{initial_values_json}}}\n"
        "      fields={fields}\n"
        "      columns={columns}\n"
        "    />\n"
        "  );\n"
        "}\n"
    )
    (base / page['file']).write_text(content, encoding='utf-8')

print(f'generated {len(pages)} pages')
